a=input()
s=""
d={}
m=0
i=0
while(i<len(a)):
    while(i<len(a)):
        if(a[i] not in s):
            s=s+a[i]
            d[a[i]]=i
        else:
            if(len(s)>m):
                m=len(s)
            s=""
            break
        i=i+1
    if(i<len(a)):
        i=d[a[i]]+1
print(m)